### ISSUE TITLE
issue with puppetlabs/apache vhost

### ISSUE THREAD

**Issue by ericsysmin** [jtopjian/puppet-reprepro#21]
When attempting to declare an apache vhost with docroot that's equal to the repo directory you will get a 

because   file { "${basedir}/${name}":
    ensure  => $ensure ? { present => directory, default => $ensure,},
    purge   => $ensure ? { present => undef,     default => true,},
    recurse => $ensure ? { present => undef,     default => true,},
    force   => $ensure ? { present => undef,     default => true,},
    mode    => '2755',
    owner   => $owner,
    group   => $group,
  }

is creating a directory that also apache::vhost is trying to do here 

  if ! defined(File[$docroot]) {
    file { $docroot:
      ensure  => directory,
      owner   => $docroot_owner,
      group   => $docroot_group,
      require => Package['httpd'],
    }

because of this you get an error 
Error: Failed to apply catalog: Duplicate declaration: File[/var/lib/apt/repo/reponame] is already declared in file /etc/puppet/environments/production/modules/apache/manifests/vhost.pp:266; cannot redeclare at /etc/puppet/environments/production/modules/reprepro/manifests/repository.pp:53

**Comment by diddi-** [comment]
I can verify that this is an issue and that it does not make any difference if 'require => Reprepro::Distribution[asdf]' is set for apache::vhost (if that is what you mean by making sure that reprepro is run before apache::vhost).

I believe this is not an execution time issue but rather an issue that puppet does not allow duplicate declarations of resources (in this case, File[$docroot] in apache::vhost and File[$basedir/$name] become the same after evaluation).

Only way to get past this afaik is to have different paths for docroot and basedir+name (which doesn't make much sense), OR relying on only one of the modules to do the job.

Or am I missing something in the setup?

**Comment by jtopjian** [comment]
Thanks for the note. Looks like my README documentation is out of date with the latest apache module.

It looks like there is a `manage_docroot` parameter in `apache::vhost`. Can you let me know if setting this to `false` helps?

https://github.com/puppetlabs/puppetlabs-apache#manage_docroot

**Comment by diddi-** [comment]
Thanks for the quick reply.

I tried now setting manage_docroot to false and now it seems to be working fine =)
Thanks!

**Comment by jtopjian** [comment]
Awesome! I'll update the README. Thank you for your help.
