### ISSUE TITLE
default for but_automatic_upgrades causes issues

### ISSUE THREAD

**Issue by matthewfischer** [jtopjian/puppet-reprepro#42]
New packages built with your default change their pin priority from 500 (previous) to 100. This broke our pinning for some keystone modules and lead to an interesting debugging day. The default should probably be 'no' or just make setting this value optional.

**Comment by jtopjian** [comment]
Hey Matt,

Ugh. Sorry about that. Is this related to #41? I was hoping that wouldn't happen. I was firmly against such a change in #35 but thought the change in #41 wouldn't have been as dangerous.

**Comment by matthewfischer** [comment]
Yes I think so. The old release file generated had this:

NotAutomatic: no

The new one with this change has this:

NotAutomatic: no
ButAutomaticUpgrades: yes

That changed the default package priority from 500 to 100. This lead to a series of unfortunate events and strange errors that boiled down to us getting an old copy of a keystone driver and not the newly built copy.

Since yes is now the default, I'm not sure how you change this at all. We hacked it to 'no' for now, which probably should have been the default to match old behavior. I will know for sure if this works how I want in a couple hours. I'm hopeful that 'no' is the same as not having it at all.

**Comment by jtopjian** [comment]
If that ends up resolving the problem, I have no problem making the default `no`. 

I fully agree that `no` should have been default from the start. I remember thinking that having it set to `yes` would end up biting me or someone in the ass. I'm now going to reference this issue whenever someone wants to make a similar change in any project I work on :smile:

**Comment by matthewfischer** [comment]
'no' fixes my issue.

before:
 *** 0.9+0~20150610200438.10~1.gbpd17719 0
        100 http://bfd01-blobmirror-001.os.cloud.twc.net/repos/keystone/20150611.33/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status

After: 
 *** 0.9+0~20150610200438.10~1.gbpd17719 0
        500 http://bfd01-blobmirror-001.os.cloud.twc.net/repos/keystone/20150611.33/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by jtopjian** [comment]
okie dokie. I'll make the change and upload a new package to the Forge tonight. I apologize about that.

**Comment by jtopjian** [comment]
Hi Matt,

The default has been set to `no` and a new package (1.6.1) has been uploaded to the Forge. Again, sorry about that. Thank you for reporting the issue, though!

Joe

**Comment by matthewfischer** [comment]
Thanks Joe!
