### ISSUE TITLE
Often fails when including package into repo

### ISSUE THREAD

**Issue by ashish1099** [jtopjian/puppet-reprepro#59]
Error comes up, whatever method I try.

1. Added package under repo/tmp/repo fails
2. su - reprepro and ran icludedeb command still fails

```gpgme gave error GPGME:32870:  Inappropriate ioctl for device
ERROR: Could not finish exporting 'jessie'!
This means that from outside your repository will still look like before (and
should still work if this old state worked), but the changes intended with this
call will not be visible until you call export directly (via reprepro export)
Changes will also get visible when something else changes the same file and
thus creates a new export of that file, but even changes to other parts of the
same distribution will not!
There have been errors!```

**Comment by leon0909** [comment]
Hi I am having the same issue,

Inside a docker container running jessy and trying to use gpg signing settings within a conf/distribution reprepro.

`<12:01:32>leon@repository:/srv/repository/ubuntu# sudo reprepro export
Exporting dapper...
Exporting dapper-testing...
Exporting hardy...
Exporting hardy-testing...
Exporting lucid...
Exporting lucid-testing...
Exporting precise...
Exporting precise-testing...
Exporting trusty...
gpgme gave error GPGME:32870:  Inappropriate ioctl for device
ERROR: Could not finish exporting 'trusty'!
There have been errors!
` 
Note: the signing is set only on trusty here.

`Settings for trusty:
Codename: trusty
Origin: My Origin Name
Components: main
Label: My Origin Repository
Architectures: i386 amd64
SignWith: XXXXXXXX
# Contents: . .gz .bz2 .xz
# Log: trusty-packages.my-origin-repo.log
Suite: trusty
`

This could be some issue with caps restrictions of the Docker... but this is the only mentioning on similar gpgme problem, Ive found in two day on google, Iam running jessy, the rest similar ones are all having to do with pacman on Arch Linux, and does not seem to give a clue.

Does somebody have an Idea of help? 

Like a 'docker run --some_cap_to_enable_option' ? 

or

 use another gpgmelib or some gpg configuration adjustment ...

**Comment by ashish1099** [comment]
@leon0909 The found the problem was not with the puppet module, it was with the login and tty access. since I was using a LXC and doing lxc-attach does not give a tty, by using ssh and running the steps it worked fine. can you do the same and try again

**Comment by leon0909** [comment]
Hi ashish1099,

It can have something to do with this, and me runnign on docker container, and Docker uses lxc as its base sublayer...

I was logged in with: nsenter
`nsenter --target $(docker inspect --format {{.State.Pid}} ${cnt_name}) --mount --uts --ipc --net --pid`

and realy had this issue. Perhaps nsenter uses the shell environment from the Docker host letting one into the container.. and the error is a result of it.

But I have just found out another workarround that very well functioned!

Here it is : One needs to mount /dev/pts, one can do this in a bash script that is getting called at the container init or call it through ~/.bashrc 

so the answer was for me : `/srv/repository/ubuntu# mount -t devpts none /dev/pts && reprepro export ` 

found it here: https://bugzilla.redhat.com/show_bug.cgi?id=1224908#c9

best regards,
Leonid

**Comment by ashish1099** [comment]
@leon0909 thats nice. we can close this issue now. :)
